#!/bin/bash
# Re-scrape Meta Model API docs (dev.meta.ai, native .md endpoints; index
# at https://dev.meta.ai/docs/llms.txt).  Same 200-with-body guard as the
# others.  Muse Code (the coding agent), Muse Glimmer (open weights) and the
# cookbook are not the API and are not scraped.
set -e
DIR="$(cd "$(dirname "$0")/pages" && pwd)"
source "$(dirname "$0")/../fetch.sh"
BASE="https://dev.meta.ai/docs"

PAGES=(
  "llms.md=/llms.txt"
  "overview.md=/overview.md"
  "quickstart.md=/quickstart.md"
  "authentication.md=/authentication.md"
  "models.md=/models.md"
  "sdks.md=/sdks.md"
  "pricing-rate-limits.md=/pricing-rate-limits.md"
  "guide--tool-calling.md=/tool-calling.md"
  "guide--tool-search.md=/tool-search.md"
  "guide--search-grounding.md=/search-grounding.md"
  "guide--image-understanding.md=/image-understanding.md"
  "guide--image-generation.md=/image-generation.md"
  "guide--speech-to-text.md=/speech-to-text.md"
  "guide--video-understanding.md=/video-understanding.md"
  "guide--file-handling.md=/file-handling.md"
  "guide--reasoning.md=/reasoning.md"
  "guide--structured-output.md=/structured-output.md"
  "guide--prompt-caching.md=/prompt-caching.md"
  "guide--token-counting.md=/token-counting.md"
  "protocols.md=/protocols.md"
  "protocols--responses.md=/protocols/responses.md"
  "protocols--chat-completions.md=/protocols/chat-completions.md"
  "protocols--messages.md=/protocols/messages.md"
  "coding-agents.md=/coding-agents.md"
  "api-reference.md=/api-reference.md"
  "error-handling.md=/error-handling.md"
  "status.md=/api-reference/status.md"
  "responses.md=/api-reference/responses.md"
  "responses--create.md=/api-reference/responses/create-response.md"
  "responses--retrieve.md=/api-reference/responses/retrieve-response.md"
  "responses--delete.md=/api-reference/responses/delete-response.md"
  "responses--cancel.md=/api-reference/responses/cancel-response.md"
  "responses--count-input-tokens.md=/api-reference/responses/count-input-tokens.md"
  "responses--schemas.md=/api-reference/responses/schemas.md"
  "chat--overview.md=/api-reference/chat-completions.md"
  "chat--create.md=/api-reference/chat-completions/create-chat-completion.md"
  "chat--schemas.md=/api-reference/chat-completions/schemas.md"
  "messages--overview.md=/api-reference/messages.md"
  "messages--create.md=/api-reference/messages/create-message.md"
  "messages--count-tokens.md=/api-reference/messages/count-tokens.md"
  "messages--schemas.md=/api-reference/messages/schemas.md"
  "files--overview.md=/api-reference/files.md"
  "files--upload.md=/api-reference/files/upload-file.md"
  "files--list.md=/api-reference/files/list-files.md"
  "files--retrieve.md=/api-reference/files/retrieve-file.md"
  "files--content.md=/api-reference/files/retrieve-file-content.md"
  "files--delete.md=/api-reference/files/delete-file.md"
  "files--schemas.md=/api-reference/files/schemas.md"
  "images--overview.md=/api-reference/images.md"
  "images--create.md=/api-reference/images/create-image.md"
  "images--edit.md=/api-reference/images/edit-image.md"
  "images--schemas.md=/api-reference/images/schemas.md"
  "voice--overview.md=/api-reference/voice.md"
  "voice--transcribe.md=/api-reference/voice/transcribe.md"
  "voice--realtime.md=/api-reference/voice/realtime.md"
  "voice--schemas.md=/api-reference/voice/schemas.md"
  "models--overview.md=/api-reference/models.md"
  "models--list.md=/api-reference/models/list-models.md"
  "models--retrieve.md=/api-reference/models/retrieve-model.md"
  "models--schemas.md=/api-reference/models/schemas.md"
)

echo "Meta Model API docs -> $DIR"
for entry in "${PAGES[@]}"; do
  fetch_page "${entry%%=*}" "${BASE}${entry#*=}"
done
fetch_summary
